export default {
  items: [
    {
      version: '1.0',
      statusCode: 200,
      result: {
        jobId: '1',
        positionName: 'Gerber Operatörü',
        companyName: 'Test2',
        durationDay: 0,
        durationDayText: 'Taze çıktı!',
        imageUrl: 'https://localhost/bluecollar/company/job/Default/6.jpg',
        countryCode: 'TR',
        countryName: 'Turkey',
        cityName: 'İstanbul',
        townName: 'Ümraniye',
        address: 'Saray Mahallesi Site Yolu Sokak No:7 34768 Ümraniye/İstanbul Turkey',
        postalCode: 34768,
        hasLatitude: true,
        hasLongitude: true,
        latitude: 41.0266502,
        longitude: 29.1157803,
        description: 'syovsvyosvyoyvsoby',
        status: 1,
      },
    },
    {
      version: '1.0',
      statusCode: 200,
      result: {
        jobId: '2',
        positionName: 'kıdemli yazilimci',
        companyName: 'Test2',
        durationDay: 0,
        durationDayText: 'Taze çıktı!',
        imageUrl: 'https://localhost/bluecollar/company/job/Default/6.jpg',
        countryCode: 'TR',
        countryName: 'Turkey',
        cityName: 'İstanbul',
        townName: 'Ümraniye',
        address: 'Saray Mahallesi Site Yolu Sokak No:7 34768 Ümraniye/İstanbul Turkey',
        postalCode: 34768,
        hasLatitude: true,
        hasLongitude: true,
        latitude: 41.0266502,
        longitude: 29.1157803,
        description: 'syovsvyosvyoyvsoby',
        status: 1,
      },
    },
    {
      version: '1.0',
      statusCode: 200,
      result: {
        jobId: '3',
        positionName: 'yazilim mühendisliği',
        companyName: 'Test3',
        durationDay: 0,
        durationDayText: 'Taze çıktı!',
        imageUrl: 'https://localhost/bluecollar/company/job/Default/6.jpg',
        countryCode: 'TR',
        countryName: 'Turkey',
        cityName: 'İstanbul',
        townName: 'Ümraniye',
        address: 'Saray Mahallesi Site Yolu Sokak No:7 34768 Ümraniye/İstanbul Turkey',
        postalCode: 34768,
        hasLatitude: true,
        hasLongitude: true,
        latitude: 41.0266502,
        longitude: 29.1157803,
        description: 'syovsvyosvyoyvsoby',
        status: 1,
      },
    },
    {
      version: '1.0',
      statusCode: 200,
      result: {
        jobId: '4',
        positionName: 'backend developer',
        companyName: 'Test4',
        durationDay: 0,
        durationDayText: 'Taze çıktı!',
        imageUrl: 'https://localhost/bluecollar/company/job/Default/6.jpg',
        countryCode: 'TR',
        countryName: 'Turkey',
        cityName: 'İstanbul',
        townName: 'Ümraniye',
        address: 'Saray Mahallesi Site Yolu Sokak No:7 34768 Ümraniye/İstanbul Turkey',
        postalCode: 34768,
        hasLatitude: true,
        hasLongitude: true,
        latitude: 41.0266502,
        longitude: 29.1157803,
        description: 'syovsvyosvyoyvsoby',
        status: 1,
      },
    },
    {
      version: '1.0',
      statusCode: 200,
      result: {
        jobId: '5',
        positionName: 'backend developer',
        companyName: 'Test5',
        durationDay: 0,
        durationDayText: 'Taze çıktı!',
        imageUrl: 'https://localhost/bluecollar/company/job/Default/6.jpg',
        countryCode: 'TR',
        countryName: 'Turkey',
        cityName: 'İstanbul',
        townName: 'Ümraniye',
        address: 'Saray Mahallesi Site Yolu Sokak No:7 34768 Ümraniye/İstanbul Turkey',
        postalCode: 34768,
        hasLatitude: true,
        hasLongitude: true,
        latitude: 41.0266502,
        longitude: 29.1157803,
        description: 'syovsvyosvyoyvsoby',
        status: 1,
      },
    },
  ],
};
